name: Node.js Main Environment Deployment

on:
  push:
    branches:
      - main

jobs:

  
  # =========================
  # PROD DEPLOYMENT
  # =========================
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to PROD
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.PROD_EC2_SSH_KEY }}

          script: |
            set -e

            echo "Deploying to PROD..."

            cd /home/ec2-user/project1-aws-ec2-cicd

            git fetch origin main
            git reset --hard origin/main
            git clean -fd

            echo "2. Checking deployed commit..."
            git rev-parse HEAD
            git log -1 --oneline

            echo "3. Installing dependencies..."
            npm install

            echo "4. Restarting PM2 application..."

            if pm2 describe node-cicd-demo > /dev/null 2>&1; then
                APP_ENV=PROD pm2 restart node-cicd-demo --update-env
            else
                APP_ENV=PROD pm2 start node-cicd-demo --update-env
            fi


            echo "PRODUCTION deployment successful!"
